### ISSUE TITLE
BE-37: Fix the bug when created a listing, calling get posting listing endpoint, returns exception.

### ISSUE THREAD

**Issue by Mik3Qiao** [ECE651-Group-15/backend#58]
As discussion during the meeting, this bug was spotted by the FE folk @Kurt-Yu , created this ticket to fix the issue when create a new customer, when calling get their posted listing endpoint, returns exception.

**Comment by tangg5** [comment]
I checked the getCustomerPostedListings function and the message format printed, it doesn't seem to be throwing exceptions, the format is not defined by the exception mapper

**Comment by Mik3Qiao** [comment]
Yeah this is related to the `toDomain` method in CustomerProfile dto
